openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /account:
    post:
      requestBody:
        description: アカウント情報
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
              example:
                userName: ton
                password: katsu
      responses:
        '200':
          description: OK
        '400':
          description: "重複"
  /login:
    post:
      requestBody:
        description: 認証情報
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
              example:
                userName: ton
                password: katsu
      responses:
        '200':
          description: OK
        '401':
          description: NG
  /room:
    post:
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  roomId:
                    type: string
        '500':
          description: Server Error
  /ws:
    get:
      description: Web Socketに接続する.
      parameters:
        - name: "roomid"
          in: "query"
          description: 接続するルームID
          required: true
          schema:
            type: "integer"
            example: 123456
      responses:
        '101':
          description: Web Socketでの通信を開始
        '400':
          description: リクエストされたルームIDを持つルームが存在しない
        '401':
          description: セッションがない (ログインしてない)
