openapi: '3.0.2'
info:
  title: API Title
  version: '1.0'
servers:
  - url: https://api.server.test/v1
paths:
  /account:
    post:
      requestBody:
        description: アカウント情報
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
              example:
                userName: ton
                password: katsu
      responses:
        '200':
          description: OK
        '400':
          description: "重複"
  /login:
    post:
      requestBody:
        description: 認証情報
        content:
          application/json:
            schema:
              type: object
              properties:
                userName:
                  type: string
                password:
                  type: string
              example:
                userName: ton
                password: katsu
      responses:
        '200':
          description: OK
        '401':
          description: NG
