name: check-server-action
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: './server'
          gofmt-flags: '-l -d'
