name: check-server-action
on: [push]
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - name: check format
        run: gofmt -l -d ./server
