name: check-server-action
on: [push]
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
      - name: check directory
        run: pwd
      - name: check format
        run: gofmt -l -d .
