name: check-server-action
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  format-check:
    runs-on: ubuntu-latest
    steps:
      - name: set up repo
        uses: actions/checkout@v3
      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'
      - name: check format
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-path: '/server'
          gofmt-path: '-l -d'
